use serde_json::json;

pub fn ui_text() -> serde_json::Value {
    json!({
        "ui_text": {
            "en": {
                "eyebrow": "Verbum Quest · Mock Quiz",
                "title": "Journey through the Word",
                "subtitle": "Learn the Good News in a playful way—journey through Salvation History.",
                "welcomeTitle": "Welcome to Verbum Quest",
                "welcomeBody": "Journey through Salvation History—Creation, Covenant, Exodus, Kingdom, the Church, Christ. This is a reduced demo you can play right away; create an account to unlock the full path and save your progress.",
                "start": "Start",
                "score": "Level",
                "question": "Question",
                "of": "of",
                "source": "Source",
                "correct": "Correct",
                "correctMsg": "You chose wisely.",
                "incorrectMsg": "Not quite.",
                "restart": "Restart",
                "next": "Next",
                "finish": "Finish",
                "playAgain": "Play again",
                "loginCta": "Login / Sign up",
                "profile": "Profile",
                "account": "Account",
                "login": "Login / Sign up",
                "guestPref": "Prefer to stay guest",
                "language": "Language",
                "guestName": "Guest pilgrim",
                "perfectTitle": "Perfect pilgrimage!",
                "perfectBody": "You answered every question. A moment of grace awaits.",
                "perfectCTA": "Spread the Good News!"
            },
            "es": {
                "eyebrow": "Verbum Quest · Quiz de prueba",
                "title": "Peregrina por la Palabra",
                "subtitle": "Aprende la Buena Nueva de forma lúdica—recorre la Historia de la Salvación.",
                "welcomeTitle": "Bienvenido a Verbum Quest",
                "welcomeBody": "Recorre la Historia de la Salvación — Creación, Alianza, Éxodo, Reino, Iglesia, Cristo. Es una demo reducida que puedes jugar ya; crea una cuenta para desbloquear todo el camino y guardar tu progreso.",
                "start": "Comenzar",
                "score": "Nivel",
                "question": "Pregunta",
                "of": "de",
                "source": "Fuente",
                "correct": "Correcta",
                "correctMsg": "Elegiste bien.",
                "incorrectMsg": "No del todo.",
                "restart": "Reiniciar",
                "next": "Siguiente",
                "finish": "Terminar",
                "playAgain": "Jugar de nuevo",
                "loginCta": "Iniciar sesión / Registrarse",
                "profile": "Perfil",
                "account": "Cuenta",
                "login": "Iniciar sesión / Registrarse",
                "guestPref": "Prefiero seguir como invitado",
                "language": "Idioma",
                "guestName": "Peregrino invitado",
                "perfectTitle": "Peregrinación perfecta",
                "perfectBody": "Respondiste todo correcto. Te aguarda un momento de gracia.",
                "perfectCTA": "¡Anuncia la Buena Nueva!"
            },
            "pt": {
                "eyebrow": "Verbum Quest · Quiz de teste",
                "title": "Caminho pela Palavra",
                "subtitle": "Aprenda a Boa Nova de forma lúdica—caminhe pela História da Salvação.",
                "welcomeTitle": "Bem-vindo ao Verbum Quest",
                "welcomeBody": "Percorra a História da Salvação — Criação, Aliança, Êxodo, Reino, Igreja, Cristo. Esta é uma demo reduzida para jogar já; crie uma conta para destravar tudo e salvar seu progresso.",
                "start": "Começar",
                "score": "Nível",
                "question": "Pergunta",
                "of": "de",
                "source": "Fonte",
                "correct": "Correta",
                "correctMsg": "Você escolheu bem.",
                "incorrectMsg": "Quase lá.",
                "restart": "Reiniciar",
                "next": "Próxima",
                "finish": "Finalizar",
                "playAgain": "Jogar novamente",
                "loginCta": "Entrar / Registrar",
                "profile": "Perfil",
                "account": "Conta",
                "login": "Entrar / Registrar",
                "guestPref": "Prefiro continuar como convidado",
                "language": "Idioma",
                "guestName": "Peregrino convidado",
                "perfectTitle": "Peregrinação perfeita",
                "perfectBody": "Você acertou tudo. Um momento de graça o aguarda.",
                "perfectCTA": "Anuncie a Boa Nova!"
            }
        }
    })
}
